name: CI - Testing Cache Anything New | Action
on:
  workflow_dispatch:
jobs:
  testing_actions:
    name: Testing Actions | Job
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      # Required action
      - uses: actions/cache@v2
        id: cache-id
        with:
          path: ${{ runner.temp }}/cache-directory-example
          key: ${{ runner.os }}-cache-hello-world-key-v1.0
      # Required action
      - uses: airvzxf/cache-anything-new-action@v1.0.1
        with:
          script: 'install.sh'
          is_cached: ${{ steps.cache-id.outputs.cache-hit }}
          cache: ${{ runner.temp }}/cache-directory-example
          snapshot: '/'
          exclude: '/boot /data /dev /mnt /proc /run /sys'
